on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
    
    - name: ðŸ“ Create .env file
      run: |
        {
          echo "APP_NAME=CCHE"
          echo "APP_ENV=production"
          echo "APP_KEY=base64:WgsgE79AeI61TjRQyjz3AbsV4/"
          echo "APP_DEBUG=false"
          echo "APP_URL=https://api.cche-ch.org"
          echo ""
          echo "LOG_CHANNEL=stack"
          echo "LOG_LEVEL=error"
          echo ""
          echo "DB_CONNECTION=mysql"
          echo "DB_HOST=localhost"
          echo "DB_PORT=3306"
          echo "DB_DATABASE=cchechor_mydatabases"
          echo "DB_USERNAME=cchechor_rachard"
          echo "DB_PASSWORD=Rachardgeek_009"
          echo ""
          echo "BROADCAST_DRIVER=log"
          echo "CACHE_DRIVER=file"
          echo "FILESYSTEM_DISK=local"
          echo "QUEUE_CONNECTION=sync"
          echo "SESSION_DRIVER=file"
          echo "SESSION_LIFETIME=120"
          echo ""
          echo "CORS_ALLOWED_ORIGINS=https://cche-ch.org"
          echo "SANCTUM_STATEFUL_DOMAINS=api.cche-ch.org"
          echo "SESSION_DOMAIN=.cche-ch.org"
          echo ""
          echo "MAIL_MAILER=smtp"
          echo "MAIL_HOST=mail.cche-ch.org"
          echo "MAIL_PORT=587"
          echo "MAIL_USERNAME=no-reply@cche-ch.org"
          echo "MAIL_PASSWORD=votre_password_smtp"
          echo "MAIL_ENCRYPTION=tls"
          echo "MAIL_FROM_ADDRESS=no-reply@cche-ch.org"
          echo "MAIL_FROM_NAME=CCHE"
          echo ""
          echo "MEMCACHED_HOST=null"
          echo "REDIS_HOST=null"
          echo ""
          echo "SESSION_SECURE_COOKIE=true"
        } > .env
    
    - name: ðŸ”¨ Build Project
      run: |
        composer install --no-dev --optimize-autoloader
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER}}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/api.cche-ch.org/
